# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-appka"
client_id = "b23565df91024902c3ef845b695e2288"
application_url = "https://universal-bridal-education-dv.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_orders, read_customers, read_publications, read_markets, read_pixels, write_pixels, read_customer_events"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://universal-bridal-education-dv.trycloudflare.com/auth/callback",
  "https://universal-bridal-education-dv.trycloudflare.com/auth/shopify/callback",
  "https://universal-bridal-education-dv.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2021-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "maksym-zubko.myshopify.com"
